export const ROBOT_TYPES = [
  'All types',
  'Industrial Robot',
  'Palletizing Robot',
  'Collaborative Robot (Cobot)',
  'Articulated Robot',
  'AGV/AMR',
  'SCARA Robot',
  'Mobile Robot',
  'AMR (Autonomous Mobile Robot)',
  'Mig Welding Robot',
  'Cobot',
  'Heavy Handling Robot',
  'Small Handling Robot',
  'Medium Handling Robot',
  'Laser Welding Robot',
  'Laser Cutting Robot',
  'SCARA'
];

export const ROBOT_BRANDS = [
  'All Brands',
  'ABB',
  'Fanuc',
  'KUKA',
  'Yaskawa',
  'Kawasaki',
  'Others'
];

export const APPLICATIONS = [
  'Packaging',
  'Machine Tending',
  'Welding',
  'Assembly',
  'Material Handling',
  'Painting',
  'Cutting',
  'Inspection'
];

export const STATES = [
  'All Locations',
  'Krishnagiri',
  'Bengaluru',
  'Coimbatore',
  'Chennai',
  'Pune',
  'Ahmedabad',
  'Germany',
  'Madurai'
];

// Mock data for robots
export const MOCK_ROBOTS = [
  {
    id: 1,
    title: "12KG Payload Yaskawa YS12-1550",
    brand: "Yaskawa",
    model: "YS12-1550",
    year: 2024,
    type: "Articulated Robot",
    payload: "12KG",
    location: "Krishnagiri",
    state: "Tamil Nadu",
    price: 1000000,
    applications: ["Packaging", "Machine Tending"],
    seller: "Verified Seller",
    image: "/api/placeholder/300/200"
  },
  {
    id: 2,
    title: "Sweet Cutting Robot - Ultrasonic",
    brand: "Unknown Brand",
    model: "Ultrasonic Cutter",
    year: 2025,
    type: "Articulated Robot",
    payload: "5KG",
    location: "Coimbatore",
    state: "Tamil Nadu",
    price: 2600000,
    applications: ["Systems and automation"],
    seller: "Unknown Seller",
    image: "/api/placeholder/300/200"
  },
  {
    id: 3,
    title: "10 Kg Payload Robotic Arm",
    brand: "Others",
    model: "10KG Arm",
    year: 2025,
    type: "Industrial Robot",
    payload: "10KG",
    location: "Chennai",
    state: "Tamil Nadu",
    price: 800000,
    applications: ["Assembly"],
    seller: "Arrowed Robotic Private Limited",
    image: "/api/placeholder/300/200"
  },
  {
    id: 4,
    title: "5 Kg Payload Robotic Arm",
    brand: "Others",
    model: "5KG Arm",
    year: 2025,
    type: "Industrial Robot",
    payload: "5KG",
    location: "Chennai",
    state: "Tamil Nadu",
    price: 450000,
    applications: ["Assembly"],
    seller: "Arrowed Robotic Private Limited",
    image: "/api/placeholder/300/200"
  },
  {
    id: 5,
    title: "Collaborative TIG Welding Robot",
    brand: "ABB",
    model: "TIG Welder",
    year: 2025,
    type: "Collaborative Robot (Cobot)",
    payload: "16KG",
    location: "Chennai",
    state: "Tamil Nadu",
    price: 1600000,
    applications: ["Welding"],
    seller: "Arrowedx Robotic Private Limited",
    verified: true,
    image: "/api/placeholder/300/200"
  },
  {
    id: 6,
    title: "Front Axle TIG Welding Robot",
    brand: "ABB",
    model: "Front Axle Welder",
    year: 2025,
    type: "Industrial Robot",
    payload: "12KG",
    location: "Chennai",
    state: "Tamil Nadu",
    price: 1200000,
    applications: ["Welding"],
    seller: "Arrowedx Robotic Private Limited",
    verified: true,
    image: "/api/placeholder/300/200"
  },
  {
    id: 7,
    title: "Heavy Payload Robotic Arm",
    brand: "Others",
    model: "Heavy Arm",
    year: 2025,
    type: "Heavy Handling Robot",
    payload: "200KG",
    location: "Pune",
    state: "Maharashtra",
    price: 13000000,
    applications: ["Material Handling"],
    seller: "Arrowedx Robotic Private Limited",
    verified: true,
    image: "/api/placeholder/300/200"
  },
  {
    id: 8,
    title: "CNC Machine Tending Robot",
    brand: "Others",
    model: "CNC Tender",
    year: 2025,
    type: "Industrial Robot",
    payload: "25KG",
    location: "Bengaluru",
    state: "Karnataka",
    price: 1800000,
    applications: ["Machine Tending"],
    seller: "Arrowedx Robotic Private Limited",
    verified: true,
    image: "/api/placeholder/300/200"
  },
  {
    id: 9,
    title: "Laser Cutting Robot System",
    brand: "KUKA",
    model: "Laser Cutter Pro",
    year: 2024,
    type: "Laser Cutting Robot",
    payload: "8KG",
    location: "Ahmedabad",
    state: "Gujarat",
    price: 2200000,
    applications: ["Cutting"],
    seller: "Tech Robotics Ltd",
    verified: true,
    image: "/api/placeholder/300/200"
  },
  {
    id: 10,
    title: "Mobile Assembly Robot",
    brand: "Fanuc",
    model: "Mobile Assembler",
    year: 2025,
    type: "Mobile Robot",
    payload: "15KG",
    location: "Germany",
    state: "International",
    price: 3500000,
    applications: ["Assembly", "Material Handling"],
    seller: "Global Robotics Inc",
    verified: true,
    image: "/api/placeholder/300/200"
  },
  {
    id: 11,
    title: "SCARA Pick and Place Robot",
    brand: "Yaskawa",
    model: "SCARA-PP",
    year: 2024,
    type: "SCARA Robot",
    payload: "3KG",
    location: "Madurai",
    state: "Tamil Nadu",
    price: 750000,
    applications: ["Assembly", "Packaging"],
    seller: "Precision Automation",
    verified: true,
    image: "/api/placeholder/300/200"
  },
  {
    id: 12,
    title: "Palletizing Robot System",
    brand: "ABB",
    model: "Palletizer Pro",
    year: 2025,
    type: "Palletizing Robot",
    payload: "50KG",
    location: "Coimbatore",
    state: "Tamil Nadu",
    price: 2800000,
    applications: ["Packaging", "Material Handling"],
    seller: "Industrial Solutions Co",
    verified: true,
    image: "/api/placeholder/300/200"
  }
];